### ISSUE TITLE
🐛 [Bug] 15초 stream안들어가는 문제 

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#29]
### Problem

transcribe가 안됨
채팅유저 먼저 들어가면 stream이 생성 안되서그럼 

나중에 로키랑 같이 만나서 해결해보기 (될때도 있어서 좀 애매함)

### Reproduction

채팅 유저 먼저 들어가고 
transcribe timeout 조건인 15초를 넘어서 stream 입력이 안되면 터짐. 

### Log

```Shell
Room created: 5cf33a2e-eff3-41
New user connected: opRIEhJlBiZcNYqtAAAh
roomname : 5cf33a2e-eff3-41
caller@test.com joined room: 5cf33a2e-eff3-41
caller@test.com joined room: 5cf33a2e-eff3-41 as chat
[RoomManager] Room 5cf33a2e-eff3-41 added.
roomname : 5cf33a2e-eff3-41
callee@parrotalk.com joined room: 5cf33a2e-eff3-41
callee@parrotalk.com joined room: 5cf33a2e-eff3-41 as voice
[RoomManager] Audio stream already exists for room: 5cf33a2e-eff3-41
[Transcribe] Starting Transcribe for room: 5cf33a2e-eff3-41
[Transcribe] Starting session for room: 5cf33a2e-eff3-41
[Transcribe] Error for room 5cf33a2e-eff3-41: BadRequestException: Your request timed out because no new audio was received for 15 seconds.
    at de_BadRequestExceptionRes (/Users/choeyunseo/Documents/kakaoBootcamp/teamMission/parrotalk_FE/node_modules/@aws-sdk/client-transcribe-streaming/dist-cjs/index.js:806:21)
    at de_BadRequestException_event (/Users/choeyunseo/Documents/kakaoBootcamp/teamMission/parrotalk_FE/node_modules/@aws-sdk/client-transcribe-streaming/dist-cjs/index.js:1019:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/choeyunseo/Documents/kakaoBootcamp/teamMission/parrotalk_FE/node_modules/@aws-sdk/client-transcribe-streaming/dist-cjs/index.js:985:30
    at async Object.deserializer (/Users/choeyunseo/Documents/kakaoBootcamp/teamMission/parrotalk_FE/node_modules/@smithy/eventstream-serde-universal/dist-cjs/index.js:127:37)
    at async _SmithyMessageDecoderStream.asyncIterator (/Users/choeyunseo/Documents/kakaoBootcamp/teamMission/parrotalk_FE/node_modules/@smithy/eventstream-codec/dist-cjs/index.js:430:28)
    at async AwsTranscribeService.startTranscribe (file:///Users/choeyunseo/Documents/kakaoBootcamp/teamMission/parrotalk_FE/src/services/AwsTranscribeService.js:45:24) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: undefined,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined
  }
}
[Transcribe] Ending session for room: 5cf33a2e-eff3-41
[RoomManager] Stream ended for room: 5cf33a2e-eff3-41
[Transcribe] Audio stream fully ended for room: 5cf33a2e-eff3-41
[RoomManager] Room 5cf33a2e-eff3-41 removed.
[Transcribe] Stream ended, sending final empty audio chunk
User disconnected: opRIEhJlBiZcNYqtAAAh
```

### Browser

Chrome

**Comment by Austin-Choi** [comment]
자신이 chat 모드일때만 audio_chunk 보내게 되있던 것 CallScreen 작업에서 처리함으로써 해결
